name: workflow


on:
  push:
    branches:
      - master
      
jobs:
  my_test:
  
    runs-on: ubuntu latest
    
    steps:
    - name: print hello massage
      run : echo "hello from test job"
    
  my_deploy:
  
    runs-on: ubuntu-latest
    needs: [my_test]
    
    steps:
    - name: print another hello
      run : echo "hello from deploy job"
    


