name: workflow
env:
  APP_NAME: "Some app"
  PACKAGE_NAME: "deploy_file-${{ github.sha }}"

on:
  push:
    branches:
      - master
      
jobs:
  my_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: print hello massage
      run : echo "hello from test job"
    - name: execute command
      run: |
        echo "hi message 1"
        echo "hi message 2"
        echo "ver: ${{ env.APP_NAME }}"
   
    - name: git clone
      uses: actions/checkout@v1
    - name: list current foler
      run: ls -la
    
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_test]
 
    
    steps:
    - name: print another hello
      run : echo "hello from deploy job"
    - name: deploy pack
      run: echo "deploy package name is ${{ env.PACKAGE_NAME }}"
      
    - name: test smth
      run: aws --version
      


